"""artists

Revision ID: 147aad73536e
Revises:
Create Date: 2023-02-20 06:39:54.083506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147aad73536e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.execute("""INSERT INTO artists (spotify_id, name)
                    VALUES
                    ('2CIMQHirSU0MQqyYHq0eOx', ''),
                    ('57dN52uHvrHOxijzpIgu3E', ''),
                    ('1vCWHaC5f2uS3yhpwWbIA6', ''),
                    ('4FVS2fGhv66N8QLEj77EEP', '') ;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
